// Generated by Enlang Mobile Compiler (.enlgm) -> Flutter / Dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
// Note: Add 'http: ^1.2.0' in pubspec.yaml if performing network requests

void main() => runApp(const PrayasPortfolioApp());

class PrayasPortfolioApp extends StatelessWidget {
  const PrayasPortfolioApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PrayasPortfolio',
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark().copyWith(
        colorScheme: ColorScheme.dark(primary: const Color(0xFF00F2FE)),
      ),
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Prayas Kumar Sahoo"),
        actions: [
          IconButton(onPressed: () {
            ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Link copied to clipboard!")));
          }, icon: const Icon(Icons.share))
        ]
      ),
      body: SingleChildScrollView(child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
          CircleAvatar(radius: 55.0, backgroundImage: NetworkImage('https://avatars.githubusercontent.com/u/100000000?v=4')),
          const SizedBox(height: 16),
          Text("PRAYAS KUMAR SAHOO", style: TextStyle(fontSize: 26, fontWeight: FontWeight.bold, color: const Color(0xFFFFFFFF))),
          Text("Java Backend Developer & Spring Boot Specialist", style: TextStyle(fontSize: 14, color: const Color(0xFF00F2FE))),
          const SizedBox(height: 10),
          Text("Specializing in microservices, enterprise architecture, MySQL, and Oracle DB.", style: TextStyle(fontSize: 13, color: const Color(0xFF94A3B8))),
          const SizedBox(height: 24),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
            ElevatedButton(onPressed: () {
              Navigator.push(context, MaterialPageRoute(builder: (_) => const ContactScreen()));
            }, child: Text("📞 Contact Me")),
            const SizedBox(width: 16),
            ElevatedButton(onPressed: () {
              ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Opening GitHub Profile...")));
            }, child: Text("🐙 GitHub"))
            ],
          ),
          const SizedBox(height: 32),
          Card(elevation: 4, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)), child: Padding(padding: const EdgeInsets.all(16), child: Column(
                children: [
                Text("Core Backend Arsenal", style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: const Color(0xFF00F2FE))),
                const SizedBox(height: 14),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                  Chip(label: Text("Java 21")),
                  Chip(label: Text("Spring Boot")),
                  Chip(label: Text("MySQL")),
                  Chip(label: Text("Oracle DB"))
                  ],
                ),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                  Chip(label: Text("REST APIs")),
                  Chip(label: Text("Microservices")),
                  Chip(label: Text("JWT Security")),
                  Chip(label: Text("Hibernate"))
                  ],
                )
                ],
              ))),
          const SizedBox(height: 24),
          Card(elevation: 4, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)), child: Padding(padding: const EdgeInsets.all(16), child: Column(
                children: [
                Text("Featured Projects", style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: const Color(0xFF00F2FE))),
                const SizedBox(height: 12),
                Text("1. Learning Management System (LMS)", style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold)),
                Text("Role-based access control, JWT auth, and automated course analytics.", style: TextStyle(fontSize: 12, color: const Color(0xFF94A3B8))),
                const SizedBox(height: 10),
                Text("2. Enterprise Payroll System", style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold)),
                Text("Financial engine automating tax deductions with strict ACID guarantees.", style: TextStyle(fontSize: 12, color: const Color(0xFF94A3B8)))
                ],
              )))
          ],
        )),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
        Navigator.push(context, MaterialPageRoute(builder: (_) => const ContactScreen()));
        },
        child: const Icon(Icons.email),
      ),
    );
  }
}

class ContactScreen extends StatefulWidget {
  const ContactScreen({super.key});

  @override
  State<ContactScreen> createState() => _ContactScreenState();
}

class _ContactScreenState extends State<ContactScreen> {
  dynamic isSent = false;
  final TextEditingController _nameFieldController = TextEditingController();
  final TextEditingController _emailFieldController = TextEditingController();
  final TextEditingController _msgFieldController = TextEditingController();

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    _nameFieldController.dispose();
    _emailFieldController.dispose();
    _msgFieldController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Get in Touch")
      ),
      body: SingleChildScrollView(child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
          Text("Send a Direct Message", style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: const Color(0xFFFFFFFF))),
          const SizedBox(height: 6),
          Text("Prayas will receive your inquiry directly.", style: TextStyle(fontSize: 13, color: const Color(0xFF94A3B8))),
          const SizedBox(height: 24),
          TextField(controller: _nameFieldController, decoration: const InputDecoration(hintText: 'Your Name')),
          const SizedBox(height: 14),
          TextField(controller: _emailFieldController, decoration: const InputDecoration(hintText: 'Your Email')),
          const SizedBox(height: 14),
          TextField(controller: _msgFieldController, decoration: const InputDecoration(hintText: 'Your Message / Project inquiry...'), maxLines: 4),
          const SizedBox(height: 24),
          ElevatedButton(onPressed: () {
            setState(() { isSent = true; });
            ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Message sent successfully! Prayas will respond soon.")));
            Navigator.pop(context);
          }, child: Text("🚀 Submit Inquiry"))
          ],
        )),
    );
  }
}
