/* Embedded C99 Runtime for Zero-Dependency Portability */
#ifndef ENLNG_RUNTIME_EMBED_H
#define ENLNG_RUNTIME_EMBED_H

static const char* ENLNG_EMBEDDED_RUNTIME =
    "/*\n"
    " * =====================================================================\n"
    " *   ENLANG SOVEREIGN PROGRAMMING LANGUAGE COMPILER (Pure C99 Native)\n"
    " *   src/enlng_runtime.h - Universal Embedded Zero-Dependency Native C99 Runtime\n"
    " *   Turing-Complete Foundation: Polymorphic Types, HashMaps, Lists,\n"
    " *   File I/O, OS/System, Math & Standard Library Built-ins.\n"
    " * =====================================================================\n"
    " */\n"
    "\n"
    "#ifndef ENLNG_RUNTIME_H\n"
    "#define ENLNG_RUNTIME_H\n"
    "\n"
    "#include <stdio.h>\n"
    "#include <stdlib.h>\n"
    "#include <stdbool.h>\n"
    "#include <stdint.h>\n"
    "#include <string.h>\n"
    "#include <math.h>\n"
    "#include <time.h>\n"
    "#include <ctype.h>\n"
    "\n"
    "#ifdef _WIN32\n"
    "#include <windows.h>\n"
    "#else\n"
    "#include <unistd.h>\n"
    "#endif\n"
    "\n"
    "/* Forward declarations */\n"
    "typedef struct EnlngVal EnlngVal;\n"
    "typedef struct EnlngList EnlngList;\n"
    "typedef struct EnlngMap EnlngMap;\n"
    "typedef struct EnlngMapEntry EnlngMapEntry;\n"
    "\n"
    "/* --- Value Types --- */\n"
    "typedef enum {\n"
    "    ENLNG_VAL_INT,\n"
    "    ENLNG_VAL_FLOAT,\n"
    "    ENLNG_VAL_STRING,\n"
    "    ENLNG_VAL_BOOL,\n"
    "    ENLNG_VAL_LIST,\n"
    "    ENLNG_VAL_MAP,\n"
    "    ENLNG_VAL_NULL\n"
    "} EnlngValType;\n"
    "\n"
    "struct EnlngVal {\n"
    "    EnlngValType type;\n"
    "    union {\n"
    "        int64_t i;\n"
    "        double f;\n"
    "        char* s;\n"
    "        bool b;\n"
    "        EnlngList* l;\n"
    "        EnlngMap* m;\n"
    "    } as;\n"
    "};\n"
    "\n"
    "struct EnlngList {\n"
    "    EnlngVal* items;\n"
    "    int count;\n"
    "    int capacity;\n"
    "};\n"
    "\n"
    "struct EnlngMapEntry {\n"
    "    char* key;\n"
    "    EnlngVal val;\n"
    "    EnlngMapEntry* next;\n"
    "};\n"
    "\n"
    "struct EnlngMap {\n"
    "    EnlngMapEntry** buckets;\n"
    "    int capacity;\n"
    "    int count;\n"
    "};\n"
    "\n"
    "/* --- Constructors --- */\n"
    "static inline EnlngVal enlng_make_int(int64_t v) {\n"
    "    EnlngVal val; val.type = ENLNG_VAL_INT; val.as.i = v; return val;\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_make_float(double v) {\n"
    "    EnlngVal val; val.type = ENLNG_VAL_FLOAT; val.as.f = v; return val;\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_make_bool(bool v) {\n"
    "    EnlngVal val; val.type = ENLNG_VAL_BOOL; val.as.b = v; return val;\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_make_null(void) {\n"
    "    EnlngVal val; val.type = ENLNG_VAL_NULL; val.as.i = 0; return val;\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_make_string(const char* s) {\n"
    "    EnlngVal val; val.type = ENLNG_VAL_STRING;\n"
    "    if (!s) { val.as.s = (char*)malloc(1); val.as.s[0] = '\\0'; return val; }\n"
    "    size_t len = strlen(s);\n"
    "    val.as.s = (char*)malloc(len + 1);\n"
    "    memcpy(val.as.s, s, len + 1);\n"
    "    return val;\n"
    "}\n"
    "\n"
    "static inline int64_t enlng_val_to_int(EnlngVal v) {\n"
    "    if (v.type == ENLNG_VAL_INT) return v.as.i;\n"
    "    if (v.type == ENLNG_VAL_FLOAT) return (int64_t)v.as.f;\n"
    "    return 0;\n"
    "}\n"
    "\n"
    "/* --- Dynamic List Operations --- */\n"
    "static inline EnlngList* enlng_list_create(void) {\n"
    "    EnlngList* list = (EnlngList*)malloc(sizeof(EnlngList));\n"
    "    list->count = 0;\n"
    "    list->capacity = 8;\n"
    "    list->items = (EnlngVal*)malloc(sizeof(EnlngVal) * list->capacity);\n"
    "    return list;\n"
    "}\n"
    "\n"
    "static inline void enlng_list_push(EnlngList* list, EnlngVal v) {\n"
    "    if (list->count >= list->capacity) {\n"
    "        list->capacity *= 2;\n"
    "        list->items = (EnlngVal*)realloc(list->items, sizeof(EnlngVal) * list->capacity);\n"
    "    }\n"
    "    list->items[list->count++] = v;\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_make_list(EnlngList* list) {\n"
    "    EnlngVal val; val.type = ENLNG_VAL_LIST; val.as.l = list; return val;\n"
    "}\n"
    "\n"
    "/* --- Hash Map Operations (DJB2 Hash Table) --- */\n"
    "static inline unsigned long enlng_hash_str(const char* str) {\n"
    "    unsigned long hash = 5381;\n"
    "    int c;\n"
    "    while ((c = *str++)) hash = ((hash << 5) + hash) + c;\n"
    "    return hash;\n"
    "}\n"
    "\n"
    "static inline EnlngMap* enlng_map_create(void) {\n"
    "    EnlngMap* m = (EnlngMap*)malloc(sizeof(EnlngMap));\n"
    "    m->capacity = 16;\n"
    "    m->count = 0;\n"
    "    m->buckets = (EnlngMapEntry**)calloc(m->capacity, sizeof(EnlngMapEntry*));\n"
    "    return m;\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_make_map(EnlngMap* m) {\n"
    "    EnlngVal val; val.type = ENLNG_VAL_MAP; val.as.m = m; return val;\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_map_get(EnlngVal v, const char* key) {\n"
    "    if (v.type != ENLNG_VAL_MAP || !v.as.m || !key) return enlng_make_null();\n"
    "    EnlngMap* m = v.as.m;\n"
    "    unsigned long h = enlng_hash_str(key) % m->capacity;\n"
    "    EnlngMapEntry* e = m->buckets[h];\n"
    "    while (e) {\n"
    "        if (strcmp(e->key, key) == 0) return e->val;\n"
    "        e = e->next;\n"
    "    }\n"
    "    return enlng_make_null();\n"
    "}\n"
    "\n"
    "static inline void enlng_map_set(EnlngVal v, const char* key, EnlngVal item) {\n"
    "    if (v.type != ENLNG_VAL_MAP || !v.as.m || !key) return;\n"
    "    EnlngMap* m = v.as.m;\n"
    "    unsigned long h = enlng_hash_str(key) % m->capacity;\n"
    "    EnlngMapEntry* e = m->buckets[h];\n"
    "    while (e) {\n"
    "        if (strcmp(e->key, key) == 0) {\n"
    "            e->val = item;\n"
    "            return;\n"
    "        }\n"
    "        e = e->next;\n"
    "    }\n"
    "    /* Add new key-value pair */\n"
    "    EnlngMapEntry* ne = (EnlngMapEntry*)malloc(sizeof(EnlngMapEntry));\n"
    "    size_t klen = strlen(key);\n"
    "    ne->key = (char*)malloc(klen + 1);\n"
    "    memcpy(ne->key, key, klen + 1);\n"
    "    ne->val = item;\n"
    "    ne->next = m->buckets[h];\n"
    "    m->buckets[h] = ne;\n"
    "    m->count++;\n"
    "}\n"
    "\n"
    "static inline bool enlng_map_has(EnlngVal v, const char* key) {\n"
    "    if (v.type != ENLNG_VAL_MAP || !v.as.m || !key) return false;\n"
    "    EnlngMap* m = v.as.m;\n"
    "    unsigned long h = enlng_hash_str(key) % m->capacity;\n"
    "    EnlngMapEntry* e = m->buckets[h];\n"
    "    while (e) {\n"
    "        if (strcmp(e->key, key) == 0) return true;\n"
    "        e = e->next;\n"
    "    }\n"
    "    return false;\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_map_keys(EnlngVal v) {\n"
    "    EnlngList* l = enlng_list_create();\n"
    "    if (v.type == ENLNG_VAL_MAP && v.as.m) {\n"
    "        EnlngMap* m = v.as.m;\n"
    "        for (int i = 0; i < m->capacity; i++) {\n"
    "            EnlngMapEntry* e = m->buckets[i];\n"
    "            while (e) {\n"
    "                enlng_list_push(l, enlng_make_string(e->key));\n"
    "                e = e->next;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    return enlng_make_list(l);\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_map_values(EnlngVal v) {\n"
    "    EnlngList* l = enlng_list_create();\n"
    "    if (v.type == ENLNG_VAL_MAP && v.as.m) {\n"
    "        EnlngMap* m = v.as.m;\n"
    "        for (int i = 0; i < m->capacity; i++) {\n"
    "            EnlngMapEntry* e = m->buckets[i];\n"
    "            while (e) {\n"
    "                enlng_list_push(l, e->val);\n"
    "                e = e->next;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    return enlng_make_list(l);\n"
    "}\n"
    "\n"
    "/* --- Container Length --- */\n"
    "static inline int64_t enlng_count_of(EnlngVal v) {\n"
    "    if (v.type == ENLNG_VAL_LIST && v.as.l) return v.as.l->count;\n"
    "    if (v.type == ENLNG_VAL_STRING && v.as.s) return (int64_t)strlen(v.as.s);\n"
    "    if (v.type == ENLNG_VAL_MAP && v.as.m) return (int64_t)v.as.m->count;\n"
    "    return 0;\n"
    "}\n"
    "\n"
    "/* --- List Get & Set --- */\n"
    "static inline EnlngVal enlng_list_get(EnlngVal v, int64_t idx) {\n"
    "    if (v.type == ENLNG_VAL_LIST && v.as.l) {\n"
    "        if (idx < 0 || idx >= v.as.l->count) return enlng_make_null();\n"
    "        return v.as.l->items[idx];\n"
    "    }\n"
    "    if (v.type == ENLNG_VAL_STRING && v.as.s) {\n"
    "        int64_t len = (int64_t)strlen(v.as.s);\n"
    "        if (idx < 0 || idx >= len) return enlng_make_null();\n"
    "        char buf[2] = { v.as.s[idx], '\\0' };\n"
    "        return enlng_make_string(buf);\n"
    "    }\n"
    "    return enlng_make_null();\n"
    "}\n"
    "\n"
    "static inline void enlng_list_set(EnlngVal v, int64_t idx, EnlngVal item) {\n"
    "    if (v.type == ENLNG_VAL_LIST && v.as.l && idx >= 0) {\n"
    "        while (v.as.l->count <= idx) {\n"
    "            enlng_list_push(v.as.l, enlng_make_null());\n"
    "        }\n"
    "        v.as.l->items[idx] = item;\n"
    "    }\n"
    "}\n"
    "\n"
    "/* --- Universal Container Get & Set (Handles Lists, Strings, and Maps) --- */\n"
    "static inline EnlngVal enlng_container_get(EnlngVal c, EnlngVal key) {\n"
    "    if (c.type == ENLNG_VAL_MAP) {\n"
    "        if (key.type == ENLNG_VAL_STRING) return enlng_map_get(c, key.as.s);\n"
    "        char buf[64]; snprintf(buf, sizeof(buf), \"%lld\", (long long)enlng_val_to_int(key));\n"
    "        return enlng_map_get(c, buf);\n"
    "    }\n"
    "    if (c.type == ENLNG_VAL_LIST || c.type == ENLNG_VAL_STRING) {\n"
    "        int64_t idx = enlng_val_to_int(key);\n"
    "        int64_t cnt = enlng_count_of(c);\n"
    "        if (idx < 0) idx += cnt;\n"
    "        return enlng_list_get(c, idx);\n"
    "    }\n"
    "    return enlng_make_null();\n"
    "}\n"
    "\n"
    "static inline void enlng_container_set(EnlngVal c, EnlngVal key, EnlngVal val) {\n"
    "    if (c.type == ENLNG_VAL_MAP) {\n"
    "        if (key.type == ENLNG_VAL_STRING) {\n"
    "            enlng_map_set(c, key.as.s, val);\n"
    "        } else {\n"
    "            char buf[64]; snprintf(buf, sizeof(buf), \"%lld\", (long long)enlng_val_to_int(key));\n"
    "            enlng_map_set(c, buf, val);\n"
    "        }\n"
    "        return;\n"
    "    }\n"
    "    if (c.type == ENLNG_VAL_LIST) {\n"
    "        int64_t idx = enlng_val_to_int(key);\n"
    "        int64_t cnt = enlng_count_of(c);\n"
    "        if (idx < 0) idx += cnt;\n"
    "        enlng_list_set(c, idx, val);\n"
    "        return;\n"
    "    }\n"
    "}\n"
    "\n"
    "/* In-place list swap */\n"
    "static inline void enlng_list_swap(EnlngVal v, int64_t i, int64_t j) {\n"
    "    if (v.type == ENLNG_VAL_LIST && v.as.l) {\n"
    "        if (i >= 0 && i < v.as.l->count && j >= 0 && j < v.as.l->count) {\n"
    "            EnlngVal temp = v.as.l->items[i];\n"
    "            v.as.l->items[i] = v.as.l->items[j];\n"
    "            v.as.l->items[j] = temp;\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* In-place list reverse */\n"
    "static inline void enlng_list_reverse(EnlngVal v) {\n"
    "    if (v.type == ENLNG_VAL_LIST && v.as.l) {\n"
    "        int left = 0;\n"
    "        int right = v.as.l->count - 1;\n"
    "        while (left < right) {\n"
    "            EnlngVal temp = v.as.l->items[left];\n"
    "            v.as.l->items[left] = v.as.l->items[right];\n"
    "            v.as.l->items[right] = temp;\n"
    "            left++; right--;\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "/* Reversal expression */\n"
    "static inline EnlngVal enlng_val_reverse(EnlngVal v) {\n"
    "    if (v.type == ENLNG_VAL_STRING && v.as.s) {\n"
    "        size_t len = strlen(v.as.s);\n"
    "        char* rev = (char*)malloc(len + 1);\n"
    "        for (size_t i = 0; i < len; i++) {\n"
    "            rev[i] = v.as.s[len - 1 - i];\n"
    "        }\n"
    "        rev[len] = '\\0';\n"
    "        EnlngVal res; res.type = ENLNG_VAL_STRING; res.as.s = rev;\n"
    "        return res;\n"
    "    }\n"
    "    if (v.type == ENLNG_VAL_LIST && v.as.l) {\n"
    "        EnlngList* copy = enlng_list_create();\n"
    "        for (int i = v.as.l->count - 1; i >= 0; i--) {\n"
    "            enlng_list_push(copy, v.as.l->items[i]);\n"
    "        }\n"
    "        return enlng_make_list(copy);\n"
    "    }\n"
    "    return v;\n"
    "}\n"
    "\n"
    "/* --- Truthiness & Comparison --- */\n"
    "static inline bool enlng_is_truthy(EnlngVal v) {\n"
    "    if (v.type == ENLNG_VAL_BOOL) return v.as.b;\n"
    "    if (v.type == ENLNG_VAL_INT) return v.as.i != 0;\n"
    "    if (v.type == ENLNG_VAL_FLOAT) return v.as.f != 0.0;\n"
    "    if (v.type == ENLNG_VAL_STRING) return v.as.s && v.as.s[0] != '\\0';\n"
    "    if (v.type == ENLNG_VAL_LIST) return v.as.l && v.as.l->count > 0;\n"
    "    if (v.type == ENLNG_VAL_MAP) return v.as.m && v.as.m->count > 0;\n"
    "    return false;\n"
    "}\n"
    "\n"
    "static inline bool enlng_vals_equal(EnlngVal a, EnlngVal b) {\n"
    "    if (a.type == ENLNG_VAL_INT && b.type == ENLNG_VAL_INT) return a.as.i == b.as.i;\n"
    "    if (a.type == ENLNG_VAL_FLOAT && b.type == ENLNG_VAL_FLOAT) return a.as.f == b.as.f;\n"
    "    if (a.type == ENLNG_VAL_INT && b.type == ENLNG_VAL_FLOAT) return (double)a.as.i == b.as.f;\n"
    "    if (a.type == ENLNG_VAL_FLOAT && b.type == ENLNG_VAL_INT) return a.as.f == (double)b.as.i;\n"
    "    if (a.type == ENLNG_VAL_BOOL && b.type == ENLNG_VAL_BOOL) return a.as.b == b.as.b;\n"
    "    if (a.type == ENLNG_VAL_STRING && b.type == ENLNG_VAL_STRING) {\n"
    "        if (!a.as.s && !b.as.s) return true;\n"
    "        if (!a.as.s || !b.as.s) return false;\n"
    "        return strcmp(a.as.s, b.as.s) == 0;\n"
    "    }\n"
    "    if (a.type == ENLNG_VAL_NULL && b.type == ENLNG_VAL_NULL) return true;\n"
    "    return false;\n"
    "}\n"
    "\n"
    "static inline bool enlng_vals_gt(EnlngVal a, EnlngVal b) {\n"
    "    if (a.type == ENLNG_VAL_INT && b.type == ENLNG_VAL_INT) return a.as.i > b.as.i;\n"
    "    if (a.type == ENLNG_VAL_FLOAT && b.type == ENLNG_VAL_FLOAT) return a.as.f > b.as.f;\n"
    "    if (a.type == ENLNG_VAL_INT && b.type == ENLNG_VAL_FLOAT) return (double)a.as.i > b.as.f;\n"
    "    if (a.type == ENLNG_VAL_FLOAT && b.type == ENLNG_VAL_INT) return a.as.f > (double)b.as.i;\n"
    "    if (a.type == ENLNG_VAL_STRING && b.type == ENLNG_VAL_STRING) return strcmp(a.as.s, b.as.s) > 0;\n"
    "    return false;\n"
    "}\n"
    "\n"
    "static inline bool enlng_vals_lt(EnlngVal a, EnlngVal b) {\n"
    "    if (a.type == ENLNG_VAL_INT && b.type == ENLNG_VAL_INT) return a.as.i < b.as.i;\n"
    "    if (a.type == ENLNG_VAL_FLOAT && b.type == ENLNG_VAL_FLOAT) return a.as.f < b.as.f;\n"
    "    if (a.type == ENLNG_VAL_INT && b.type == ENLNG_VAL_FLOAT) return (double)a.as.i < b.as.f;\n"
    "    if (a.type == ENLNG_VAL_FLOAT && b.type == ENLNG_VAL_INT) return a.as.f < (double)b.as.i;\n"
    "    if (a.type == ENLNG_VAL_STRING && b.type == ENLNG_VAL_STRING) return strcmp(a.as.s, b.as.s) < 0;\n"
    "    return false;\n"
    "}\n"
    "\n"
    "static inline bool enlng_vals_gte(EnlngVal a, EnlngVal b) {\n"
    "    return enlng_vals_gt(a, b) || enlng_vals_equal(a, b);\n"
    "}\n"
    "\n"
    "static inline bool enlng_vals_lte(EnlngVal a, EnlngVal b) {\n"
    "    return enlng_vals_lt(a, b) || enlng_vals_equal(a, b);\n"
    "}\n"
    "\n"
    "/* In-place list sort */\n"
    "static inline void enlng_list_sort(EnlngVal v, bool descending) {\n"
    "    if (v.type == ENLNG_VAL_LIST && v.as.l) {\n"
    "        int n = v.as.l->count;\n"
    "        for (int i = 0; i < n - 1; i++) {\n"
    "            for (int j = 0; j < n - i - 1; j++) {\n"
    "                bool should_swap = descending ? \n"
    "                    enlng_vals_lt(v.as.l->items[j], v.as.l->items[j+1]) : \n"
    "                    enlng_vals_gt(v.as.l->items[j], v.as.l->items[j+1]);\n"
    "                if (should_swap) {\n"
    "                    EnlngVal tmp = v.as.l->items[j];\n"
    "                    v.as.l->items[j] = v.as.l->items[j+1];\n"
    "                    v.as.l->items[j+1] = tmp;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "static inline const char* enlng_val_to_str_buf(EnlngVal v, char* buf, size_t sz) {\n"
    "    if (v.type == ENLNG_VAL_STRING && v.as.s) return v.as.s;\n"
    "    if (v.type == ENLNG_VAL_INT) {\n"
    "        snprintf(buf, sz, \"%lld\", (long long)v.as.i);\n"
    "        return buf;\n"
    "    }\n"
    "    if (v.type == ENLNG_VAL_FLOAT) {\n"
    "        snprintf(buf, sz, \"%g\", v.as.f);\n"
    "        return buf;\n"
    "    }\n"
    "    if (v.type == ENLNG_VAL_BOOL) {\n"
    "        return v.as.b ? \"true\" : \"false\";\n"
    "    }\n"
    "    return \"\";\n"
    "}\n"
    "\n"
    "/* --- Arithmetic --- */\n"
    "static inline EnlngVal enlng_val_add(EnlngVal a, EnlngVal b) {\n"
    "    if (a.type == ENLNG_VAL_INT && b.type == ENLNG_VAL_INT) return enlng_make_int(a.as.i + b.as.i);\n"
    "    if (a.type == ENLNG_VAL_FLOAT || b.type == ENLNG_VAL_FLOAT) {\n"
    "        if (a.type != ENLNG_VAL_STRING && b.type != ENLNG_VAL_STRING) {\n"
    "            double da = (a.type == ENLNG_VAL_FLOAT) ? a.as.f : (double)a.as.i;\n"
    "            double db = (b.type == ENLNG_VAL_FLOAT) ? b.as.f : (double)b.as.i;\n"
    "            return enlng_make_float(da + db);\n"
    "        }\n"
    "    }\n"
    "    if (a.type == ENLNG_VAL_STRING || b.type == ENLNG_VAL_STRING) {\n"
    "        char buf_a[128]; char buf_b[128];\n"
    "        const char* sa = enlng_val_to_str_buf(a, buf_a, sizeof(buf_a));\n"
    "        const char* sb = enlng_val_to_str_buf(b, buf_b, sizeof(buf_b));\n"
    "        size_t la = strlen(sa); size_t lb = strlen(sb);\n"
    "        char* comb = (char*)malloc(la + lb + 1);\n"
    "        memcpy(comb, sa, la);\n"
    "        memcpy(comb + la, sb, lb);\n"
    "        comb[la + lb] = '\\0';\n"
    "        EnlngVal res; res.type = ENLNG_VAL_STRING; res.as.s = comb;\n"
    "        return res;\n"
    "    }\n"
    "    return enlng_make_int(0);\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_val_sub(EnlngVal a, EnlngVal b) {\n"
    "    if (a.type == ENLNG_VAL_INT && b.type == ENLNG_VAL_INT) return enlng_make_int(a.as.i - b.as.i);\n"
    "    double da = (a.type == ENLNG_VAL_FLOAT) ? a.as.f : (double)a.as.i;\n"
    "    double db = (b.type == ENLNG_VAL_FLOAT) ? b.as.f : (double)b.as.i;\n"
    "    return enlng_make_float(da - db);\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_val_mul(EnlngVal a, EnlngVal b) {\n"
    "    if (a.type == ENLNG_VAL_INT && b.type == ENLNG_VAL_INT) return enlng_make_int(a.as.i * b.as.i);\n"
    "    double da = (a.type == ENLNG_VAL_FLOAT) ? a.as.f : (double)a.as.i;\n"
    "    double db = (b.type == ENLNG_VAL_FLOAT) ? b.as.f : (double)b.as.i;\n"
    "    return enlng_make_float(da * db);\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_val_div(EnlngVal a, EnlngVal b) {\n"
    "    if (a.type == ENLNG_VAL_INT && b.type == ENLNG_VAL_INT) {\n"
    "        if (b.as.i == 0) return enlng_make_int(0);\n"
    "        return enlng_make_int(a.as.i / b.as.i);\n"
    "    }\n"
    "    double da = (a.type == ENLNG_VAL_FLOAT) ? a.as.f : (double)a.as.i;\n"
    "    double db = (b.type == ENLNG_VAL_FLOAT) ? b.as.f : (double)b.as.i;\n"
    "    if (db == 0.0) return enlng_make_float(0.0);\n"
    "    return enlng_make_float(da / db);\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_val_mod(EnlngVal a, EnlngVal b) {\n"
    "    if (a.type == ENLNG_VAL_INT && b.type == ENLNG_VAL_INT && b.as.i != 0) {\n"
    "        return enlng_make_int(a.as.i % b.as.i);\n"
    "    }\n"
    "    return enlng_make_int(0);\n"
    "}\n"
    "\n"
    "/* --- Stream Printing --- */\n"
    "static inline void enlng_print_val(EnlngVal v) {\n"
    "    switch (v.type) {\n"
    "        case ENLNG_VAL_INT:\n"
    "            printf(\"%lld\", (long long)v.as.i);\n"
    "            break;\n"
    "        case ENLNG_VAL_FLOAT:\n"
    "            printf(\"%.6g\", v.as.f);\n"
    "            break;\n"
    "        case ENLNG_VAL_STRING:\n"
    "            printf(\"%s\", v.as.s ? v.as.s : \"\");\n"
    "            break;\n"
    "        case ENLNG_VAL_BOOL:\n"
    "            printf(\"%s\", v.as.b ? \"true\" : \"false\");\n"
    "            break;\n"
    "        case ENLNG_VAL_LIST:\n"
    "            printf(\"[\");\n"
    "            if (v.as.l) {\n"
    "                for (int i = 0; i < v.as.l->count; i++) {\n"
    "                    enlng_print_val(v.as.l->items[i]);\n"
    "                    if (i < v.as.l->count - 1) printf(\", \");\n"
    "                }\n"
    "            }\n"
    "            printf(\"]\");\n"
    "            break;\n"
    "        case ENLNG_VAL_MAP:\n"
    "            printf(\"{\");\n"
    "            if (v.as.m) {\n"
    "                int shown = 0;\n"
    "                for (int i = 0; i < v.as.m->capacity; i++) {\n"
    "                    EnlngMapEntry* e = v.as.m->buckets[i];\n"
    "                    while (e) {\n"
    "                        if (shown > 0) printf(\", \");\n"
    "                        printf(\"\\\"%s\\\": \", e->key);\n"
    "                        enlng_print_val(e->val);\n"
    "                        shown++;\n"
    "                        e = e->next;\n"
    "                    }\n"
    "                }\n"
    "            }\n"
    "            printf(\"}\");\n"
    "            break;\n"
    "        case ENLNG_VAL_NULL:\n"
    "            printf(\"null\");\n"
    "            break;\n"
    "    }\n"
    "}\n"
    "\n"
    "/* --- Input --- */\n"
    "static inline EnlngVal enlng_ask(const char* prompt) {\n"
    "    if (prompt && prompt[0] != '\\0') {\n"
    "        printf(\"%s\", prompt);\n"
    "        fflush(stdout);\n"
    "    }\n"
    "    char buffer[1024];\n"
    "    if (!fgets(buffer, sizeof(buffer), stdin)) {\n"
    "        return enlng_make_string(\"\");\n"
    "    }\n"
    "    size_t len = strlen(buffer);\n"
    "    if (len > 0 && (buffer[len - 1] == '\\n' || buffer[len - 1] == '\\r')) {\n"
    "        buffer[len - 1] = '\\0';\n"
    "        if (len > 1 && buffer[len - 2] == '\\r') buffer[len - 2] = '\\0';\n"
    "    }\n"
    "    return enlng_make_string(buffer);\n"
    "}\n"
    "\n"
    "/* ===================================================================== */\n"
    "/*   NATIVE BUILT-IN STANDARD LIBRARY FUNCTIONS                          */\n"
    "/* ===================================================================== */\n"
    "\n"
    "/* --- Math Built-ins --- */\n"
    "static inline EnlngVal enlng_builtin_sqrt(EnlngVal v) {\n"
    "    double d = (v.type == ENLNG_VAL_INT) ? (double)v.as.i : v.as.f;\n"
    "    return enlng_make_float(sqrt(d));\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_pow(EnlngVal base, EnlngVal exp) {\n"
    "    double b = (base.type == ENLNG_VAL_INT) ? (double)base.as.i : base.as.f;\n"
    "    double e = (exp.type == ENLNG_VAL_INT) ? (double)exp.as.i : exp.as.f;\n"
    "    return enlng_make_float(pow(b, e));\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_abs(EnlngVal v) {\n"
    "    if (v.type == ENLNG_VAL_INT) {\n"
    "        return enlng_make_int(v.as.i < 0 ? -v.as.i : v.as.i);\n"
    "    }\n"
    "    return enlng_make_float(fabs(v.as.f));\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_floor(EnlngVal v) {\n"
    "    double d = (v.type == ENLNG_VAL_INT) ? (double)v.as.i : v.as.f;\n"
    "    return enlng_make_int((int64_t)floor(d));\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_ceil(EnlngVal v) {\n"
    "    double d = (v.type == ENLNG_VAL_INT) ? (double)v.as.i : v.as.f;\n"
    "    return enlng_make_int((int64_t)ceil(d));\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_round(EnlngVal v) {\n"
    "    double d = (v.type == ENLNG_VAL_INT) ? (double)v.as.i : v.as.f;\n"
    "    return enlng_make_int((int64_t)round(d));\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_min(EnlngVal a, EnlngVal b) {\n"
    "    return enlng_vals_lt(a, b) ? a : b;\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_max(EnlngVal a, EnlngVal b) {\n"
    "    return enlng_vals_gt(a, b) ? a : b;\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_random_number(EnlngVal low, EnlngVal high) {\n"
    "    int64_t l = enlng_val_to_int(low);\n"
    "    int64_t h = enlng_val_to_int(high);\n"
    "    if (h < l) { int64_t t = l; l = h; h = t; }\n"
    "    int64_t diff = h - l + 1;\n"
    "    if (diff <= 0) return enlng_make_int(l);\n"
    "    return enlng_make_int(l + (rand() % diff));\n"
    "}\n"
    "\n"
    "/* --- File I/O Built-ins --- */\n"
    "static inline EnlngVal enlng_builtin_read_file(EnlngVal path) {\n"
    "    if (path.type != ENLNG_VAL_STRING || !path.as.s) return enlng_make_string(\"\");\n"
    "    FILE* f = fopen(path.as.s, \"rb\");\n"
    "    if (!f) return enlng_make_string(\"\");\n"
    "    fseek(f, 0, SEEK_END);\n"
    "    long len = ftell(f);\n"
    "    fseek(f, 0, SEEK_SET);\n"
    "    char* buf = (char*)malloc(len + 1);\n"
    "    if (buf) {\n"
    "        fread(buf, 1, len, f);\n"
    "        buf[len] = '\\0';\n"
    "    }\n"
    "    fclose(f);\n"
    "    EnlngVal res = enlng_make_string(buf ? buf : \"\");\n"
    "    if (buf) free(buf);\n"
    "    return res;\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_write_file(EnlngVal path, EnlngVal content) {\n"
    "    if (path.type != ENLNG_VAL_STRING || !path.as.s) return enlng_make_bool(false);\n"
    "    FILE* f = fopen(path.as.s, \"wb\");\n"
    "    if (!f) return enlng_make_bool(false);\n"
    "    const char* data = (content.type == ENLNG_VAL_STRING && content.as.s) ? content.as.s : \"\";\n"
    "    fwrite(data, 1, strlen(data), f);\n"
    "    fclose(f);\n"
    "    return enlng_make_bool(true);\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_append_file(EnlngVal path, EnlngVal content) {\n"
    "    if (path.type != ENLNG_VAL_STRING || !path.as.s) return enlng_make_bool(false);\n"
    "    FILE* f = fopen(path.as.s, \"ab\");\n"
    "    if (!f) return enlng_make_bool(false);\n"
    "    const char* data = (content.type == ENLNG_VAL_STRING && content.as.s) ? content.as.s : \"\";\n"
    "    fwrite(data, 1, strlen(data), f);\n"
    "    fclose(f);\n"
    "    return enlng_make_bool(true);\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_file_exists(EnlngVal path) {\n"
    "    if (path.type != ENLNG_VAL_STRING || !path.as.s) return enlng_make_bool(false);\n"
    "    FILE* f = fopen(path.as.s, \"r\");\n"
    "    if (f) { fclose(f); return enlng_make_bool(true); }\n"
    "    return enlng_make_bool(false);\n"
    "}\n"
    "\n"
    "/* --- System & OS Built-ins --- */\n"
    "static inline EnlngVal enlng_builtin_time_now(void) {\n"
    "    return enlng_make_int((int64_t)time(NULL));\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_sleep(EnlngVal sec) {\n"
    "    int64_t ms = (int64_t)(enlng_val_to_int(sec) * 1000);\n"
    "#ifdef _WIN32\n"
    "    Sleep((DWORD)ms);\n"
    "#else\n"
    "    usleep((useconds_t)(ms * 1000));\n"
    "#endif\n"
    "    return enlng_make_null();\n"
    "}\n"
    "\n"
    "/* --- Container Operations Built-ins --- */\n"
    "static inline EnlngVal enlng_builtin_append(EnlngVal list, EnlngVal item) {\n"
    "    if (list.type == ENLNG_VAL_LIST && list.as.l) {\n"
    "        enlng_list_push(list.as.l, item);\n"
    "    }\n"
    "    return list;\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_pop(EnlngVal list) {\n"
    "    if (list.type == ENLNG_VAL_LIST && list.as.l && list.as.l->count > 0) {\n"
    "        EnlngVal last = list.as.l->items[list.as.l->count - 1];\n"
    "        list.as.l->count--;\n"
    "        return last;\n"
    "    }\n"
    "    return enlng_make_null();\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_keys(EnlngVal map) {\n"
    "    return enlng_map_keys(map);\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_values(EnlngVal map) {\n"
    "    return enlng_map_values(map);\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_has_key(EnlngVal map, EnlngVal key) {\n"
    "    const char* k = (key.type == ENLNG_VAL_STRING && key.as.s) ? key.as.s : \"\";\n"
    "    return enlng_make_bool(enlng_map_has(map, k));\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_len(EnlngVal v) {\n"
    "    return enlng_make_int(enlng_count_of(v));\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_split(EnlngVal str, EnlngVal sep) {\n"
    "    EnlngList* res = enlng_list_create();\n"
    "    if (str.type != ENLNG_VAL_STRING || !str.as.s) return enlng_make_list(res);\n"
    "    const char* s = str.as.s;\n"
    "    const char* d = (sep.type == ENLNG_VAL_STRING && sep.as.s) ? sep.as.s : \" \";\n"
    "    size_t dlen = strlen(d);\n"
    "    if (dlen == 0) {\n"
    "        /* Split into individual characters */\n"
    "        size_t slen = strlen(s);\n"
    "        for (size_t i = 0; i < slen; i++) {\n"
    "            char ch[2] = { s[i], '\\0' };\n"
    "            enlng_list_push(res, enlng_make_string(ch));\n"
    "        }\n"
    "        return enlng_make_list(res);\n"
    "    }\n"
    "    char* copy = (char*)malloc(strlen(s) + 1);\n"
    "    strcpy(copy, s);\n"
    "    char* token = strtok(copy, d);\n"
    "    while (token) {\n"
    "        enlng_list_push(res, enlng_make_string(token));\n"
    "        token = strtok(NULL, d);\n"
    "    }\n"
    "    free(copy);\n"
    "    return enlng_make_list(res);\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_join(EnlngVal list, EnlngVal sep) {\n"
    "    if (list.type != ENLNG_VAL_LIST || !list.as.l) return enlng_make_string(\"\");\n"
    "    const char* d = (sep.type == ENLNG_VAL_STRING && sep.as.s) ? sep.as.s : \"\";\n"
    "    size_t dlen = strlen(d);\n"
    "    size_t total_len = 0;\n"
    "    for (int i = 0; i < list.as.l->count; i++) {\n"
    "        EnlngVal item = list.as.l->items[i];\n"
    "        if (item.type == ENLNG_VAL_STRING && item.as.s) total_len += strlen(item.as.s);\n"
    "        if (i < list.as.l->count - 1) total_len += dlen;\n"
    "    }\n"
    "    char* buf = (char*)malloc(total_len + 1);\n"
    "    buf[0] = '\\0';\n"
    "    for (int i = 0; i < list.as.l->count; i++) {\n"
    "        EnlngVal item = list.as.l->items[i];\n"
    "        if (item.type == ENLNG_VAL_STRING && item.as.s) strcat(buf, item.as.s);\n"
    "        if (i < list.as.l->count - 1) strcat(buf, d);\n"
    "    }\n"
    "    EnlngVal res = enlng_make_string(buf);\n"
    "    free(buf);\n"
    "    return res;\n"
    "}\n"
    "\n"
    "static inline EnlngVal enlng_builtin_contains(EnlngVal coll, EnlngVal item) {\n"
    "    if (coll.type == ENLNG_VAL_STRING && coll.as.s && item.type == ENLNG_VAL_STRING && item.as.s) {\n"
    "        return enlng_make_bool(strstr(coll.as.s, item.as.s) != NULL);\n"
    "    }\n"
    "    if (coll.type == ENLNG_VAL_LIST && coll.as.l) {\n"
    "        for (int i = 0; i < coll.as.l->count; i++) {\n"
    "            if (enlng_vals_equal(coll.as.l->items[i], item)) return enlng_make_bool(true);\n"
    "        }\n"
    "        return enlng_make_bool(false);\n"
    "    }\n"
    "    if (coll.type == ENLNG_VAL_MAP && coll.as.m && item.type == ENLNG_VAL_STRING && item.as.s) {\n"
    "        return enlng_make_bool(enlng_map_has(coll, item.as.s));\n"
    "    }\n"
    "    return enlng_make_bool(false);\n"
    "}\n"
    "\n"
    "#endif /* ENLNG_RUNTIME_H */\n"
;

#endif /* ENLNG_RUNTIME_EMBED_H */
