"""enlgm Code Emitter.

Translates the Flutter / Dart AST (from ENLGMParser) into standard, clean,
compile-ready Dart source code targeting Flutter apps (lib/main.dart).
"""

from typing import List, Dict, Any, Optional
from .ast_nodes import (
    ASTNode, MobileRootNode, FlutterImportNode, AppDefNode, ScreenDefNode,
    WidgetNode, TextWidgetNode, IconWidgetNode, ImageWidgetNode, AvatarWidgetNode,
    ButtonWidgetNode, InputWidgetNode, SpacerWidgetNode, DividerWidgetNode,
    ChipWidgetNode, ProgressWidgetNode, ControlWidgetNode, ListViewWidgetNode,
    GridViewWidgetNode, AppBarNode, BottomNavNode, BottomNavItem, DrawerNode,
    DrawerItem, NavigationNode, StateDeclNode, StateAssignNode, ToastFeedbackNode,
    NetworkCallNode, RawDartNode, WidgetBlueprintNode, BlueprintInstanceNode,
    CallFunctionNode, MethodDefNode
)

def _hex_to_dart_color(hex_str: str) -> str:
    """Converts #00f2fe or #fff to Color(0xFF00F2FE) or Colors.xxx."""
    clean = hex_str.strip('"\' #')
    if len(clean) == 3:
        clean = "".join([c * 2 for c in clean])
    if len(clean) == 6:
        return f"const Color(0xFF{clean.upper()})"
    elif len(clean) == 8:
        return f"const Color(0x{clean.upper()})"
    
    # Named colors
    named_map = {
        "white": "Colors.white",
        "black": "Colors.black",
        "red": "Colors.red",
        "blue": "Colors.blue",
        "green": "Colors.green",
        "grey": "Colors.grey",
        "gray": "Colors.grey",
        "transparent": "Colors.transparent"
    }
    return named_map.get(clean.lower(), f"const Color(0xFF{clean.upper()})")

class ENLGMEmitter:
    """Emits clean Dart / Flutter code from MobileRootNode."""

    def __init__(self, root: MobileRootNode):
        self.root = root
        self.input_controllers: List[str] = []

    def emit(self) -> str:
        lines: List[str] = []

        # 1. Imports
        lines.append("// Generated by Enlang Mobile Compiler (.enlgm) -> Flutter / Dart")
        lines.append("import 'package:flutter/material.dart';")

        has_http = False
        for imp in self.root.imports:
            if imp.package_name == "http":
                has_http = True
                lines.append("import 'package:http/http.dart' as http;")
            elif imp.package_name == "google_fonts":
                lines.append("import 'package:google_fonts/google_fonts.dart';")
            elif imp.package_name == "provider":
                lines.append("import 'package:provider/provider.dart';")
            elif not imp.is_flutter:
                alias_clause = f" as {imp.as_alias}" if imp.as_alias else ""
                lines.append(f"import 'package:{imp.package_name}/{imp.package_name}.dart'{alias_clause};")

        # Auto-import http if any NetworkCallNode is present in AST
        if not has_http:
            lines.append("// Note: Add 'http: ^1.2.0' in pubspec.yaml if performing network requests")

        lines.append("")

        # 2. Main Entry Point
        app_node = self.root.app or AppDefNode(name="EnlangApp")
        app_class_name = f"{app_node.name}App"
        lines.append(f"void main() => runApp(const {app_class_name}());")
        lines.append("")

        # 3. MaterialApp Widget
        lines.append(f"class {app_class_name} extends StatelessWidget {{")
        lines.append(f"  const {app_class_name}({{super.key}});")
        lines.append("")
        lines.append("  @override")
        lines.append("  Widget build(BuildContext context) {")
        lines.append("    return MaterialApp(")
        lines.append(f"      title: '{app_node.name}',")
        lines.append("      debugShowCheckedModeBanner: false,")
        
        theme_expr = "ThemeData.dark()" if app_node.theme == "dark" else "ThemeData.light()"
        if app_node.primary_color:
            color_dart = _hex_to_dart_color(app_node.primary_color)
            lines.append(f"      theme: {theme_expr}.copyWith(")
            lines.append(f"        colorScheme: ColorScheme.{app_node.theme}(primary: {color_dart}),")
            lines.append("      ),")
        else:
            lines.append(f"      theme: {theme_expr},")

        lines.append(f"      home: const {app_node.home_screen}(),")
        lines.append("    );")
        lines.append("  }")
        lines.append("}")
        lines.append("")

        # 4. Custom Blueprints (Custom Widgets)
        for bp in self.root.blueprints:
            lines.append(self._emit_blueprint(bp))
            lines.append("")

        # 5. Screens
        for screen in self.root.screens:
            lines.append(self._emit_screen(screen))
            lines.append("")

        # 6. Raw Dart Blocks
        for raw in self.root.raw_dart_blocks:
            lines.append(raw.code)
            lines.append("")

        return "\n".join(lines)

    def _emit_blueprint(self, bp: WidgetBlueprintNode) -> str:
        lines = [
            f"class {bp.name} extends StatelessWidget {{",
        ]
        # Fields
        for p in bp.params:
            lines.append(f"  final dynamic {p};")
        
        # Constructor
        param_list = ", ".join([f"this.{p}" for p in bp.params])
        lines.append(f"  const {bp.name}({{{param_list}}}, {{super.key}});")
        lines.append("")
        lines.append("  @override")
        lines.append("  Widget build(BuildContext context) {")
        if bp.body:
            child_code = self._emit_widget(bp.body[0], indent=2)
            lines.append(f"    return {child_code};")
        else:
            lines.append("    return const SizedBox.shrink();")
        lines.append("  }")
        lines.append("}")
        return "\n".join(lines)

    def _emit_screen(self, screen: ScreenDefNode) -> str:
        if screen.is_stateful:
            return self._emit_stateful_screen(screen)
        else:
            return self._emit_stateless_screen(screen)

    def _emit_stateless_screen(self, screen: ScreenDefNode) -> str:
        lines = [
            f"class {screen.name} extends StatelessWidget {{",
            f"  const {screen.name}({{super.key}});",
            "",
            "  @override",
            "  Widget build(BuildContext context) {",
            "    return Scaffold("
        ]

        # App Bar
        if screen.app_bar:
            lines.append(f"      appBar: {self._emit_appbar(screen.app_bar, indent=3)},")

        # Body
        body_widget = self._emit_body_widget(screen.body, indent=3)
        lines.append(f"      body: {body_widget},")

        # FAB
        if screen.fab:
            lines.append(f"      floatingActionButton: {self._emit_fab(screen.fab, indent=3)},")

        # Bottom Bar
        if screen.bottom_bar:
            lines.append(f"      bottomNavigationBar: {self._emit_bottom_bar(screen.bottom_bar, indent=3)},")

        # Drawer
        if screen.drawer:
            lines.append(f"      drawer: {self._emit_drawer(screen.drawer, indent=3)},")

        lines.append("    );")
        lines.append("  }")
        lines.append("}")
        return "\n".join(lines)

    def _emit_stateful_screen(self, screen: ScreenDefNode) -> str:
        state_class_name = f"_{screen.name}State"
        lines = [
            f"class {screen.name} extends StatefulWidget {{",
            f"  const {screen.name}({{super.key}});",
            "",
            "  @override",
            f"  State<{screen.name}> createState() => {state_class_name}();",
            "}",
            "",
            f"class {state_class_name} extends State<{screen.name}> {{"
        ]

        # State Variables
        for var in screen.state_vars:
            lines.append(f"  dynamic {var.name} = {var.initial_val};")

        # Collect Input Controllers in screen body
        controllers = self._collect_input_controllers(screen.body)
        for ctrl_id in controllers:
            lines.append(f"  final TextEditingController _{ctrl_id}Controller = TextEditingController();")

        # Lifecycle Init
        if screen.lifecycle_inits or controllers:
            lines.append("")
            lines.append("  @override")
            lines.append("  void initState() {")
            lines.append("    super.initState();")
            for init_node in screen.lifecycle_inits:
                lines.append(f"    {self._emit_action(init_node, indent=2)}")
            lines.append("  }")

        # Lifecycle Dispose
        lines.append("")
        lines.append("  @override")
        lines.append("  void dispose() {")
        for ctrl_id in controllers:
            lines.append(f"    _{ctrl_id}Controller.dispose();")
        for disp_node in screen.lifecycle_disposes:
            lines.append(f"    {self._emit_action(disp_node, indent=2)}")
        lines.append("    super.dispose();")
        lines.append("  }")

        # Custom Methods
        for method in screen.methods:
            params_str = ", ".join(method.params)
            lines.append("")
            lines.append(f"  void {method.name}({params_str}) {{")
            for stmt in method.body:
                lines.append(f"    {self._emit_action(stmt, indent=2)}")
            lines.append("  }")

        # Build Method
        lines.append("")
        lines.append("  @override")
        lines.append("  Widget build(BuildContext context) {")
        lines.append("    return Scaffold(")

        # App Bar
        if screen.app_bar:
            lines.append(f"      appBar: {self._emit_appbar(screen.app_bar, indent=3)},")

        # Body
        body_widget = self._emit_body_widget(screen.body, indent=3)
        lines.append(f"      body: {body_widget},")

        # FAB
        if screen.fab:
            lines.append(f"      floatingActionButton: {self._emit_fab(screen.fab, indent=3)},")

        # Bottom Bar
        if screen.bottom_bar:
            lines.append(f"      bottomNavigationBar: {self._emit_bottom_bar(screen.bottom_bar, indent=3)},")

        # Drawer
        if screen.drawer:
            lines.append(f"      drawer: {self._emit_drawer(screen.drawer, indent=3)},")

        lines.append("    );")
        lines.append("  }")
        lines.append("}")
        return "\n".join(lines)

    def _collect_input_controllers(self, nodes: List[ASTNode]) -> List[str]:
        ctrls = []
        for n in nodes:
            if isinstance(n, InputWidgetNode):
                ctrls.append(n.id_name)
            elif isinstance(n, WidgetNode):
                ctrls.extend(self._collect_input_controllers(n.children))
        return list(dict.fromkeys(ctrls))

    def _emit_body_widget(self, body_nodes: List[ASTNode], indent: int) -> str:
        pad = "  " * indent
        if not body_nodes:
            return "const SizedBox.shrink()"
        if len(body_nodes) == 1:
            return self._emit_widget(body_nodes[0], indent=indent)
        else:
            children_str = ",\n".join([f"{pad}  {self._emit_widget(c, indent + 1)}" for c in body_nodes])
            return f"Column(\n{pad}  children: [\n{children_str}\n{pad}  ],\n{pad})"

    def _emit_widget(self, node: ASTNode, indent: int = 0) -> str:
        pad = "  " * indent

        # ── Text Widget ──
        if isinstance(node, TextWidgetNode):
            style_parts = []
            if "size" in node.props:
                style_parts.append(f"fontSize: {node.props['size']}")
            if "bold" in node.props:
                style_parts.append("fontWeight: FontWeight.bold")
            if "italic" in node.props:
                style_parts.append("fontStyle: FontStyle.italic")
            if "color" in node.props:
                style_parts.append(f"color: {_hex_to_dart_color(node.props['color'])}")

            style_clause = f", style: TextStyle({', '.join(style_parts)})" if style_parts else ""
            align_clause = ""
            if "align" in node.props:
                a = node.props["align"].lower()
                align_map = {"center": "TextAlign.center", "left": "TextAlign.left", "right": "TextAlign.right"}
                if a in align_map:
                    align_clause = f", textAlign: {align_map[a]}"

            # Handle variable expression vs literal string
            text_val = node.text_expr
            if not (text_val.startswith('"') or text_val.startswith("'")):
                text_val = f"{text_val}.toString()"

            return f"Text({text_val}{align_clause}{style_clause})"

        # ── Icon Widget ──
        elif isinstance(node, IconWidgetNode):
            icon_id = node.icon_name.lower().replace("-", "_")
            parts = [f"Icons.{icon_id}"]
            if "size" in node.props:
                parts.append(f"size: {node.props['size']}")
            if "color" in node.props:
                parts.append(f"color: {_hex_to_dart_color(node.props['color'])}")
            return f"Icon({', '.join(parts)})"

        # ── Image Widget ──
        elif isinstance(node, ImageWidgetNode):
            path_str = f"'{node.path_or_url}'"
            parts = [path_str]
            if node.width:
                parts.append(f"width: {node.width}")
            if node.height:
                parts.append(f"height: {node.height}")
            if node.source_type == "asset":
                return f"Image.asset({', '.join(parts)})"
            else:
                return f"Image.network({', '.join(parts)})"

        # ── Avatar Widget ──
        elif isinstance(node, AvatarWidgetNode):
            parts = []
            if node.size:
                radius = float(node.size) / 2
                parts.append(f"radius: {radius}")
            if node.source_type == "network":
                parts.append(f"backgroundImage: NetworkImage('{node.value}')")
            elif node.source_type == "asset":
                parts.append(f"backgroundImage: AssetImage('{node.value}')")
            elif node.source_type == "initials":
                parts.append(f"child: Text('{node.value}')")
            return f"CircleAvatar({', '.join(parts)})"

        # ── Button Widget ──
        elif isinstance(node, ButtonWidgetNode):
            action_code = self._emit_action_block(node.on_tap_body, indent + 1)
            label = node.label_expr or "'Button'"
            if node.btn_type == "text":
                return f"TextButton(onPressed: () {{\n{action_code}\n{pad}}}, child: Text({label}))"
            elif node.btn_type == "icon":
                icon_id = (node.icon_name or "star").lower().replace("-", "_")
                return f"IconButton(onPressed: () {{\n{action_code}\n{pad}}}, icon: const Icon(Icons.{icon_id}))"
            else:
                return f"ElevatedButton(onPressed: () {{\n{action_code}\n{pad}}}, child: Text({label}))"

        # ── Input Widget ──
        elif isinstance(node, InputWidgetNode):
            hint_str = f"hintText: '{node.placeholder}'"
            lines_str = f", maxLines: {node.lines}" if node.lines > 1 else ""
            obscure_str = ", obscureText: true" if node.is_hidden else ""
            return f"TextField(controller: _{node.id_name}Controller, decoration: const InputDecoration({hint_str}){lines_str}{obscure_str})"

        # ── Spacer & Divider ──
        elif isinstance(node, SpacerWidgetNode):
            if node.is_expandable:
                return "const Spacer()"
            elif node.height:
                return f"const SizedBox(height: {node.height})"
            elif node.width:
                return f"const SizedBox(width: {node.width})"
            return "const SizedBox.shrink()"

        elif isinstance(node, DividerWidgetNode):
            color_str = f"color: {_hex_to_dart_color(node.color)}" if node.color else ""
            return f"Divider({color_str})" if color_str else "const Divider()"

        # ── Chip & Progress ──
        elif isinstance(node, ChipWidgetNode):
            return f"Chip(label: Text({node.label_expr}))"

        elif isinstance(node, ProgressWidgetNode):
            if node.is_circular:
                return "const CircularProgressIndicator()"
            return "const LinearProgressIndicator()"

        # ── Layout Containers (Column, Row, Stack, Center, Scroll, Card, Container, Padding) ──
        elif isinstance(node, WidgetNode):
            children_str = ",\n".join([f"{pad}  {self._emit_widget(c, indent + 1)}" for c in node.children])
            
            if node.widget_type in ("column", "column_center", "column_spaced"):
                align = ""
                if node.widget_type == "column_center" or "centered" in node.props:
                    align = "mainAxisAlignment: MainAxisAlignment.center,\n" + pad + "  "
                elif node.widget_type == "column_spaced" or "spaced" in node.props:
                    align = "mainAxisAlignment: MainAxisAlignment.spaceBetween,\n" + pad + "  "
                return f"Column(\n{pad}  {align}children: [\n{children_str}\n{pad}  ],\n{pad})"

            elif node.widget_type in ("row", "row_center", "row_spaced"):
                align = ""
                if node.widget_type == "row_center" or "centered" in node.props:
                    align = "mainAxisAlignment: MainAxisAlignment.center,\n" + pad + "  "
                elif node.widget_type == "row_spaced" or "spaced" in node.props:
                    align = "mainAxisAlignment: MainAxisAlignment.spaceBetween,\n" + pad + "  "
                return f"Row(\n{pad}  {align}children: [\n{children_str}\n{pad}  ],\n{pad})"

            elif node.widget_type == "stack":
                return f"Stack(\n{pad}  children: [\n{children_str}\n{pad}  ],\n{pad})"

            elif node.widget_type == "center":
                child = self._emit_widget(node.children[0], indent + 1) if node.children else "const SizedBox.shrink()"
                return f"Center(child: {child})"

            elif node.widget_type == "scroll":
                child = self._emit_body_widget(node.children, indent + 1)
                return f"SingleChildScrollView(child: {child})"

            elif node.widget_type == "safearea":
                child = self._emit_body_widget(node.children, indent + 1)
                return f"SafeArea(child: {child})"

            elif node.widget_type == "expanded":
                child = self._emit_body_widget(node.children, indent + 1)
                flex_str = f"flex: {node.props.get('flex', 1)}, " if 'flex' in node.props else ""
                return f"Expanded({flex_str}child: {child})"

            elif node.widget_type == "card":
                child = self._emit_body_widget(node.children, indent + 1)
                elev = f"elevation: {node.props.get('elevation', 4)}, " if 'elevation' in node.props else ""
                shape_str = ""
                if "radius" in node.props or "corner_radius" in node.props:
                    r = node.props.get("radius") or node.props.get("corner_radius")
                    shape_str = f"shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular({r})), "
                return f"Card({elev}{shape_str}child: {child})"

            elif node.widget_type == "container":
                child = self._emit_body_widget(node.children, indent + 1)
                w_str = f"width: {node.props['width']}, " if 'width' in node.props else ""
                h_str = f"height: {node.props['height']}, " if 'height' in node.props else ""
                
                dec_parts = []
                if "color" in node.props:
                    dec_parts.append(f"color: {_hex_to_dart_color(node.props['color'])}")
                if "radius" in node.props or "corner_radius" in node.props:
                    r = node.props.get("radius") or node.props.get("corner_radius")
                    dec_parts.append(f"borderRadius: BorderRadius.circular({r})")
                
                dec_str = f"decoration: BoxDecoration({', '.join(dec_parts)}), " if dec_parts else ""
                return f"Container({w_str}{h_str}{dec_str}child: {child})"

            elif node.widget_type in ("padding", "padding_all", "padding_symmetric"):
                child = self._emit_body_widget(node.children, indent + 1)
                val = node.props.get("padding", "16")
                return f"Padding(padding: const EdgeInsets.all({val}), child: {child})"

        # ── Lists & Grids ──
        elif isinstance(node, ListViewWidgetNode):
            template_code = self._emit_body_widget(node.template, indent + 2)
            return (
                f"ListView.builder(\n"
                f"{pad}  itemCount: ({node.items_expr} as List).length,\n"
                f"{pad}  itemBuilder: (context, index) {{\n"
                f"{pad}    final {node.item_var} = {node.items_expr}[index];\n"
                f"{pad}    return {template_code};\n"
                f"{pad}  }},\n"
                f"{pad})"
            )

        elif isinstance(node, GridViewWidgetNode):
            children_str = ",\n".join([f"{pad}  {self._emit_widget(c, indent + 1)}" for c in node.children])
            return (
                f"GridView.count(\n"
                f"{pad}  crossAxisCount: {node.columns},\n"
                f"{pad}  mainAxisSpacing: {node.gap}.0,\n"
                f"{pad}  crossAxisSpacing: {node.gap}.0,\n"
                f"{pad}  children: [\n{children_str}\n{pad}  ],\n"
                f"{pad})"
            )

        return "const SizedBox.shrink()"

    def _emit_action_block(self, actions: List[ASTNode], indent: int) -> str:
        pad = "  " * indent
        if not actions:
            return f"{pad}// No action"
        lines = []
        for a in actions:
            lines.append(f"{pad}{self._emit_action(a, indent)}")
        return "\n".join(lines)

    def _emit_action(self, node: ASTNode, indent: int) -> str:
        # Navigation
        if isinstance(node, NavigationNode):
            if node.action == "push":
                return f"Navigator.push(context, MaterialPageRoute(builder: (_) => const {node.target_screen}()));"
            elif node.action == "clear":
                return f"Navigator.pushAndRemoveUntil(context, MaterialPageRoute(builder: (_) => const {node.target_screen}()), (_) => false);"
            elif node.action == "replace":
                return f"Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const {node.target_screen}()));"
            elif node.action == "pop":
                return "Navigator.pop(context);"
            elif node.action == "pop_result":
                return f"Navigator.pop(context, {node.data_expr or 'true'});"

        # State Mutation
        elif isinstance(node, StateAssignNode):
            return f"setState(() {{ {node.target} {node.op} {node.value}; }});"

        # Toast / Snackbar / Alert Feedback
        elif isinstance(node, ToastFeedbackNode):
            if node.feedback_type in ("toast", "snackbar"):
                msg_val = node.message_expr
                if not (msg_val.startswith('"') or msg_val.startswith("'")):
                    msg_val = f"{msg_val}.toString()"
                return f"ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text({msg_val})));"
            elif node.feedback_type == "alert":
                return (
                    f"showDialog(context: context, builder: (ctx) => AlertDialog(\n"
                    f"  title: Text({node.message_expr}),\n"
                    f"  actions: [\n"
                    f"    TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('OK')),\n"
                    f"  ],\n"
                    f"));"
                )

        # Network Call
        elif isinstance(node, NetworkCallNode):
            lines = [
                f"http.get(Uri.parse({node.url_expr})).then(({node.on_success_param}) {{",
            ]
            for s in node.on_success_body:
                lines.append(f"  {self._emit_action(s, indent + 1)}")
            lines.append("}).catchError((" + node.on_failure_param + ") {")
            for f in node.on_failure_body:
                lines.append(f"  {self._emit_action(f, indent + 1)}")
            lines.append("});")
            return "\n".join(lines)

        # Raw Dart
        elif isinstance(node, RawDartNode):
            return node.code

        return "// action"

    def _emit_appbar(self, app_bar: AppBarNode, indent: int) -> str:
        pad = "  " * indent
        actions_str = ""
        if app_bar.actions:
            acts = ",\n".join([f"{pad}    {self._emit_widget(a, indent + 2)}" for a in app_bar.actions])
            actions_str = f",\n{pad}  actions: [\n{acts}\n{pad}  ]"
        return f"AppBar(\n{pad}  title: Text({app_bar.title_expr}){actions_str}\n{pad})"

    def _emit_fab(self, fab: ButtonWidgetNode, indent: int) -> str:
        pad = "  " * indent
        action_code = self._emit_action_block(fab.on_tap_body, indent + 1)
        icon_id = (fab.icon_name or "add").lower().replace("-", "_")
        return (
            f"FloatingActionButton(\n"
            f"{pad}  onPressed: () {{\n{action_code}\n{pad}  }},\n"
            f"{pad}  child: const Icon(Icons.{icon_id}),\n"
            f"{pad})"
        )

    def _emit_bottom_bar(self, nav: BottomNavNode, indent: int) -> str:
        pad = "  " * indent
        items_code = []
        for it in nav.items:
            icon_id = it.icon_name.lower().replace("-", "_")
            items_code.append(f"BottomNavigationBarItem(icon: Icon(Icons.{icon_id}), label: '{it.label}')")
        items_str = f",\n{pad}    ".join(items_code)
        return (
            f"BottomNavigationBar(\n"
            f"{pad}  items: const [\n{pad}    {items_str}\n{pad}  ],\n"
            f"{pad})"
        )

    def _emit_drawer(self, drawer: DrawerNode, indent: int) -> str:
        pad = "  " * indent
        return f"Drawer(\n{pad}  child: ListView(\n{pad}    children: const [DrawerHeader(child: Text('Menu'))],\n{pad}  ),\n{pad})"
